name: deploy

on:
  workflow_call:
    inputs:
      command:
        type: string
        required: true
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cdk-workshop
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'
          cache-dependency-path: cdk-workshop/package-lock.json

      - run: npm ci
      - run: npm run build

      - name: Set branch name
        id: environmentname
        run: echo ::set-output name=environment_name ::${GITHUB_REF#refs/*/} # ${GITHUB_REF##*/}
      - name: environment name set
        run: echo ${{ steps.environmentname.outputs.environment_name }}

      - run: ./node_modules/aws-cdk/bin/cdk ${{inputs.command}} --require-approval never
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-west-2'
          deployment_environment: ${{ steps.environmentname.outputs.environment_name }}
          deployment_commitSha: ${{ github.sha }}
