name: run cdk command

on:
  workflow_call:
    inputs:
      command:
        type: string
        required: true
      args:
        type: string
        required: true
      ref:
        type: string
        required: true
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  cdk-command:
    name: cdk ${{inputs.command}}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cdk-workshop
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: spa/build/**/*
          key: spa-${{ github.ref }}-${{github.sha}}

      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'
          cache-dependency-path: cdk-workshop/package-lock.json

      - run: npm ci
      - run: npm run build

      - run: ./node_modules/aws-cdk/bin/cdk ${{inputs.command}} ${{inputs.args}} --outputs-file outputs.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-west-2'
          deployment_environment: ${{ inputs.ref }}
          deployment_commitSha: ${{ github.sha }}
