name: deploy

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
          cache: 'npm'
          cache-dependency-path: 'spa/package-lock.json'
      - run: npm ci
        working-directory: ./spa
      - run: npm run build
        working-directory: ./spa
      - uses: actions/cache@v3
        with:
          path: spa/build/**/*
          key: spa-${{ github.ref }}-${{github.sha}}

  deploy:
    needs: build
    uses: ./.github/workflows/cdk.yml
    with:
      command: deploy
      args: --require-approval never
      ref: ${{github.ref_name}}
    secrets:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
