name: destroy

on:
  delete:

jobs:
  destroy:
    uses: ./.github/workflows/cdk.yml
    with:
      command: destroy
    secrets:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
